### ISSUE TITLE
Change to_binary to to_bytes

### ISSUE THREAD

**Issue by janus** [althea-mesh/serde-rlp#8]
The name to_binary does not completely reflect what to code returns. It seems like to_bytes or something close to that would be better.

**Comment by mpapierski** [comment]
Hey @janus,

Thanks for reporting this issue. I think the current name fits the purpose well enough. It takes a number and converts it to its binary form. You're right that it returns bytes, but I think *binary* is accurate enough for what it does. Its also based on the official design document which you can read here: https://github.com/ethereum/wiki/wiki/RLP

**Comment by mpapierski** [comment]
@janus I'm closing this one because of lack of activity. If you have any more suggestions I'm happy to help!
